name: 'Publish all release assets'
description: 'Upload multiple release assets'
author: 'boxpositron'
inputs:
  release_config:
    description: 'Path / filetype config'
    required: true
  tag_name:
    description: 'Specify tag name'
    required: true
  release_name:
    description: 'Specify release name'
    required: false
  overwrite:
    description: 'Overwrite existing assets'
    required: false
  draft:
    description: 'Create release as draft'
    required: false
  prerelease:
    description: 'Mark release as prerelease'
    required: false
outputs:
  browser_download_urls:
    description: 'Download URLs for uploaded assets'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'upload'
  color: 'green'
